Traceback (most recent call last):
  File "main.py", line 125, in <module>
    run_testcase(args.testcase, args)
  File "main.py", line 115, in run_testcase
    run(sa)
  File "main.py", line 105, in run
    ans = get_ans(solve_args)
  File "/home/matulni/Documents/coding_various/google_hash_2022/hashcode2022-one-pizza/util.py", line 146, in get_ans
    ans = sol_fn(inp, solve_args)
  File "/home/matulni/Documents/coding_various/google_hash_2022/hashcode2022-one-pizza/solvers/sa.py", line 64, in solve
    pizzaChainOld = gen_pop_init(ns.NIng, flag=flag, fId=fId, Nc =prevScore)#0 all 1s, 1 file, else random
NameError: name 'prevScore' is not defined
